name: example-quiet
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:

  cypress-run-v10:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests with `quiet` parameter
      - name: Cache NPM and Cypress 📦
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Cypress 📥
        run: npm i https://cdn.cypress.io/beta/npm/10.0.0/linux-x64/10.0-release-04e5d70d48a1337b702f53ac9677350167eb7ae6/cypress.tgz
      - name: Cypress run
        uses: ./
        with:
          working-directory: cypress/e2e/examples
          quiet: true